#!/usr/bin/env node

import * as streamconsumers from "node:stream/consumers";
import process from "node:process";
import util from "node:util";
import OpenAI from "./library/OpenAI.js";
import * as Execute from "./library/Execute.js";

let tools = { execute: Execute };

async function callTool(name, args) {
  let tool = tools[name];
  if (tool === undefined)
    throw new Error(`Tool not found: ${name}`);

  console.log(`${name.toUpperCase()} ${tool.argsToString(args)}`);

  try {
    return await tool.call(args);
  } catch (error) {
    return { error: error.message };
  }
}

function message(message, options = {}) {
  if (options.type !== undefined) {
    console.log(`${options.type.toUpperCase()} ${message}`);
  } else {
    console.log();
    console.log(message);
    console.log();
  }
}

function modelRunner(model) {
  if (model.startsWith("gpt-")) {
    return OpenAI({
      apiKey: process.env.OPENAI_API_KEY,
      model,
      tools: Object.entries(tools).map(([ name, tool ]) => ({ type: "function", ...tool.schema })),
      callTool,
      message
    });
  }

  throw new Error(`Unknown model name: ${model}`);
}

async function main() {
  let prompt = {};

  let { values, positionals } = util.parseArgs({
    options: {
      model: { type: "string", default: "gpt-5.2-codex" },
      system: { type: "string", multiple: true }
    },
    allowPositionals: true
  });

  let run = modelRunner(values.model);

  if (values.system !== undefined)
    prompt.system = values.system;

  if (positionals.length > 0)
    prompt.user = positionals;

  if (!process.stdin.isTTY)
    prompt.user.push(await streamconsumers.text(process.stdin));

  let r = await run(prompt, tools, message);
  console.log(`DONE ${r.tokens} tokens`);
}

try {
  await main(process.argv.slice(2));
} catch (error) {
  console.error(error.stack);
}
